### ISSUE TITLE
"Timeout has occurred" when trying to use the mediator

### ISSUE THREAD

**Issue by jack-robson** [animo/animo-mediator#22]
I can issue a credential locally using the `mediator.dev.animo.id` invitation url.

But when I run `yarn dev` to get a mediator using this repo, I can't get the new ngrok invitation url to work.

The `yarn dev` output looks promising:

```
me@ME animo-mediator % yarn dev
yarn run v1.22.21
warning ../../../package.json: No license field
$ ts-node dev
Got ngrok url: https://REDACTED.ngrok.app
2023-12-02 18:43:33.907  INFO  [DIDComm Chat src/agent.ts:71  createAgent] Using SQlite storage 
{
  walletId: 'REDACTED'
}
2023-12-02 18:43:33.912  WARN [DIDComm Chat   AskarModule.register] The '@aries-framework/askar' module is experimental and could have unexpected breaking changes. When using this module, make sure to use strict versions for all @aries-framework packages. 
2023-12-02 18:43:33.915  INFO  [DIDComm Chat   undefined.constructor] Creating agent with config 
{
  agentConfig: {
    label: 'Animo Mediator',
    endpoints: [
      'https://REDACTED.ngrok.app',
      'wss://REDACTED.ngrok.app'
    ],
    walletConfig: {
      id: 'REDACTED',
      key: '[*****]',
      storage: {}
    },
    useDidSovPrefixWhereAllowed: true,
    logger: 1,
    autoUpdateStorageOnStartup: true,
    didCommMimeType: 'application/ssi-agent-wire',
    agentDependencies: true
  }
}
2023-12-02 18:43:33.919  INFO  [DIDComm Chat   WalletApi.initialize] Initializing wallet 'REDACTED' 
{
  id: 'REDACTED',
  key: '[*****]',
  storage: {}
}
2023-12-02 18:43:34.482  DEBUG [DIDComm Chat   AskarWallet._open] Wallet 'REDACTED' opened with handle '1' 
2023-12-02 18:43:34.484  INFO  [DIDComm Chat   initialize] Agent storage is up to date. 
2023-12-02 18:43:34.486  DEBUG [DIDComm Chat   HttpInboundTransport.start] Starting HTTP inbound transport 
{
  port: 3000
}
2023-12-02 18:43:34.488  DEBUG [DIDComm Chat   WsInboundTransport.start] Starting WS inbound transport 
{
  endpoint: 'wss://REDACTED.ngrok.app'
}
2023-12-02 18:43:34.489  DEBUG [DIDComm Chat   HttpOutboundTransport.start] Starting HTTP outbound transport 
2023-12-02 18:43:34.489  DEBUG [DIDComm Chat   WsOutboundTransport.start] Starting WS outbound transport 
2023-12-02 18:43:34.490  DEBUG [DIDComm Chat   MediatorApi.initialize] Mediator routing record not loaded yet, retrieving from storage 
2023-12-02 18:43:34.492  INFO  [DIDComm Chat src/index.ts:7 undefined.<anonymous>] Agent started 
2023-12-02 18:43:34.495  INFO  [DIDComm Chat src/index.ts:31 undefined.<anonymous>] Out of band invitation url: 

        https://REDACTED.ngrok.app/invite?oob=VALID_LOOKING_ACCESS_TOKEN 
```

Visiting in my browser: `https://REDACTED.ngrok.app/invite?oob=VALID_LOOKING_ACCESS_TOKEN` also looks promising. I get `Missing or invalid _oobid` which is the same thing what I see if I visit the `mediator.dev.animo.id` invitation url.

After running my issue credential script locally using the new ngrok url, it gets stuck at the start of the mediator connection attempt:

```
INFO: Agent storage is up to date.
DEBUG: Starting HTTP outbound transport
DEBUG: Starting WS outbound transport
DEBUG: Provision mediation with invitation {
  "mediatorInvitationUrl": "https://REDACTED.ngrok.app/invite?oob=VALID_LOOKING_ACCESS_TOKEN"
}
Error
    at _super (.../node_modules/rxjs/src/internal/util/createErrorClass.ts:13:22)
    at new TimeoutErrorImpl (.../node_modules/rxjs/src/internal/operators/timeout.ts:91:7)
    at timeoutErrorFactory (.../node_modules/rxjs/src/internal/operators/timeout.ts:404:9)
    at .../node_modules/rxjs/src/internal/operators/timeout.ts:349:15
    at AsyncAction.<anonymous> (.../node_modules/rxjs/src/internal/util/executeSchedule.ts:27:5)
    at AsyncAction._execute (.../node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:120:12)
    at AsyncAction.execute (.../node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:95:24)
    at AsyncScheduler.flush (.../node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:40:27)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7) {
  message: 'Timeout has occurred',
  info: { meta: null, lastValue: null, seen: 0 }
}
```

Any advice?

**Comment by jack-robson** [comment]
Changing the WALLET_NAME in the mediator and restarting it resolved the issue. 

AFJ appears to cache the url for a mediator using a specific name inside the connections. 

When it runs through this core code in the client:

```
  protected async getMediationConnection(mediatorInvitationUrl: string) {
    const outOfBandInvitation = await this.oob.parseInvitation(mediatorInvitationUrl)
    const outOfBandRecord = await this.oob.findByReceivedInvitationId(outOfBandInvitation.id)
    const [connection] = outOfBandRecord ? await this.connections.findAllByOutOfBandId(outOfBandRecord.id) : []
```

It comes back with a connection used previously, but it doesn't realise that connection is now invalid because I've changed the mediator URL since then. 

It instead waits for it to try to connect, which it won't be able to. 

If it finds an old connection, checking it has the same URL might be helpful to invalidate it. 

It's late here but I will try to confirm this tomorrow and submit a PR in the AFJ repo.
